"""Initial migrations

Revision ID: 15443c1c7d8c
Revises: 
Create Date: 2024-09-18 22:13:52.307318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15443c1c7d8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractual_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_contractual_employees_email'), 'contractual_employees', ['email'], unique=True)
    op.create_index(op.f('ix_contractual_employees_first_name'), 'contractual_employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_contractual_employees_last_name'), 'contractual_employees', ['last_name'], unique=False)
    op.create_table('regular_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('number_of_leaves', sa.Integer(), nullable=False),
    sa.Column('benefits', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_regular_employees_email'), 'regular_employees', ['email'], unique=True)
    op.create_index(op.f('ix_regular_employees_first_name'), 'regular_employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_regular_employees_last_name'), 'regular_employees', ['last_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regular_employees_last_name'), table_name='regular_employees')
    op.drop_index(op.f('ix_regular_employees_first_name'), table_name='regular_employees')
    op.drop_index(op.f('ix_regular_employees_email'), table_name='regular_employees')
    op.drop_table('regular_employees')
    op.drop_index(op.f('ix_contractual_employees_last_name'), table_name='contractual_employees')
    op.drop_index(op.f('ix_contractual_employees_first_name'), table_name='contractual_employees')
    op.drop_index(op.f('ix_contractual_employees_email'), table_name='contractual_employees')
    op.drop_table('contractual_employees')
    # ### end Alembic commands ###
